apiVersion: v1
kind: Service
metadata:
  name: test-clickhouse-proxy-test-part-b-0
  namespace: clickhouse
  labels:
    app: test-clickhouse-proxy
spec:
  ports:
  - port: 9000
    name: test-clickhouse-proxy
  clusterIP: None # Headless Service
  selector:
    app: test-clickhouse-proxy-test-part-b-0