apiVersion: v1
kind: ConfigMap
metadata:
  name: test-clickhouse-proxy-test-part-b
  namespace: clickhouse
data:
  config.json: |
    {
      "listen": ":9000",
      "upstream": "test-clickhouse-test-part-b:9000",
      "stats_interval": "30s",
      "dial_timeout": "5s",
      "idle_timeout": "5m",
      "log_queries": true,
      "log_data": false,
      "max_query_log_bytes": 300,
      "max_data_log_bytes": 200
    }