apiVersion: v1
kind: Service
metadata:
  name: test-clickhouse-proxy-test-part-a-0
  labels:
    app: test-clickhouse-proxy
spec:
  ports:
  - port: 9000
    name: test-clickhouse-proxy
  clusterIP: None # Headless Service
  selector:
    app: test-clickhouse-proxy-test-part-a-0