apiVersion: v1
kind: Service
metadata:
  name: test-clickhouse-proxy-extra-usage-0-1-0
  labels:
    app: test-clickhouse-proxy
spec:
  ports:
  - port: 9000
    name: test-clickhouse-proxy
  - port: 9091
    name: metrics
  clusterIP: None # Headless Service
  selector:
    app: test-clickhouse-proxy-extra-usage-0-1-0
