apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-clickhouse-proxy-extra-usage-0-0-0
  namespace: clickhouse
  labels:
    app: test-clickhouse-proxy-extra-usage-0-0-0
    component: test-clickhouse-proxy
spec:
  replicas: 1 
  serviceName: test-clickhouse-proxy-extra-usage-0-0-0
  selector:
    matchLabels:
      app: test-clickhouse-proxy-extra-usage-0-0-0
  template:
    metadata:
      labels:
        app: test-clickhouse-proxy-extra-usage-0-0-0
        component: test-clickhouse-proxy
        clickhouse.altinity.com/app: chop
        clickhouse.altinity.com/chi: clickhouse-extra
        clickhouse.altinity.com/cluster: extra-usage
        clickhouse.altinity.com/namespace: clickhouse
        clickhouse.altinity.com/ready: "yes"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      
      containers:
      - name: proxy
        image: us-west1-docker.pkg.dev/sentio-352722/sentio/clickhouse-proxy:b6f0c4a
        imagePullPolicy: Always
        
        volumeMounts:
        - name: config
          mountPath: /app/config.json
          subPath: config.json
        
        ports:
        - name: clickhouse
          containerPort: 9000
          protocol: TCP
        
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        resources:
          requests:
            cpu: "8"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "16Gi"
      
      volumes:
      - name: config
        configMap:
          name: test-clickhouse-proxy-extra-usage-0-0-0
